// Export pages
export 'home_page/home_page_widget.dart' show HomePageWidget;
export 'inicio/inicio_widget.dart' show InicioWidget;
export 'funciones/funciones_widget.dart' show FuncionesWidget;
export 'peliculas/peliculas_widget.dart' show PeliculasWidget;
export 'contrasenaolvidada/contrasenaolvidada_widget.dart'
    show ContrasenaolvidadaWidget;
export 'crearcuenta/crearcuenta_widget.dart' show CrearcuentaWidget;
export 'configuracion/configuracion_widget.dart' show ConfiguracionWidget;
export 'jurassic/jurassic_widget.dart' show JurassicWidget;
export 'chipndale/chipndale_widget.dart' show ChipndaleWidget;
export 'raya/raya_widget.dart' show RayaWidget;
export 'asesino/asesino_widget.dart' show AsesinoWidget;
export 'dogg/dogg_widget.dart' show DoggWidget;
export 'doctor/doctor_widget.dart' show DoctorWidget;
export 'everything/everything_widget.dart' show EverythingWidget;
export 'sonic/sonic_widget.dart' show SonicWidget;
export 'badboys/badboys_widget.dart' show BadboysWidget;
export 'tomyjerry/tomyjerry_widget.dart' show TomyjerryWidget;
export 'topgun/topgun_widget.dart' show TopgunWidget;
export 'uncharted/uncharted_widget.dart' show UnchartedWidget;
export 'mitchells/mitchells_widget.dart' show MitchellsWidget;
export 'ruega/ruega_widget.dart' show RuegaWidget;
export 'mortal/mortal_widget.dart' show MortalWidget;
export 'everythingd/everythingd_widget.dart' show EverythingdWidget;
export 'tiposmalosd/tiposmalosd_widget.dart' show TiposmalosdWidget;
export 'tomyjerryd/tomyjerryd_widget.dart' show TomyjerrydWidget;
export 'chipydaled/chipydaled_widget.dart' show ChipydaledWidget;
export 'topgund/topgund_widget.dart' show TopgundWidget;
export 'conclusion/conclusion_widget.dart' show ConclusionWidget;
export 'cuentaempleados/cuentaempleados_widget.dart' show CuentaempleadosWidget;
